export const constants = {
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    PRICES_PRODUCTS: 'PRICES_PRODUCTS',
    SAVE_SUM: 'SAVE_SUM',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
    COST_DELIVERY: 'COST_DELIVERY',
    SAVE_NUMBERS: 'SAVE_NUMBERS',
};